### ISSUE TITLE
Error in example .trades

### ISSUE THREAD

**Issue by Mangiafuoco** [PyWaves/PyWaves#1]
Running example:

>>> trades = WAVES_BTC.trades(10)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxxxxx/.local/lib/python2.7/site-packages/pywaves/asset.py", line 116, in trades
    return self._getMarketData('/api/trades/%s/%s/%d' % (a1, a2, limit))
NameError: global name 'a1' is not defined
```

All other code from this section work fine.

**Comment by PyWaves** [comment]
Thanks for reporting this issue! It's been fixed in 0.7.8 release

**Comment by ivo1981** [comment]
I don't know if I'm doing something wrong or if there's an issue with the code but I'm unable to run the example code.
If I use this example:
import pywaves as pw

# set the asset pair
WAVES_BTC = pw.AssetPair(pw.WAVES, pw.BTC)

# get last price and volume
print("%s %s" % (WAVES_BTC.last(), WAVES_BTC.volume()))

# get ticker
ticker = WAVES_BTC.ticker()
print(ticker['24h_open'])
print(ticker['24h_vwap'])

# get last 10 trades
trades = WAVES_BTC.trades(10)
for t in trades:
	print("%s %s %s %s" % (t['buyer'], t['seller'], t['price'], t['amount']))
	
# get last 10 daily OHLCV candles
ohlcv = WAVES_BTC.candles(1440, 10)
for t in ohlcv:
	print("%s %s %s %s %s" % (t['open'], t['high'], t['low'], t['close'], t['volume']))

I get error;
WAVES_BTC = pw.AssetPair(pw.WAVES, pw.BTC)
AttributeError: 'module' object has no attribute 'BTC'

This can easely be fixt by adding:
BTC = pw.Asset('4ZzED8WJXsvuo2MEm2BmZ87Azw8Sx7TVC6ufSUA5LyTV')

and changing
WAVES_BTC = pw.AssetPair(pw.WAVES, pw.BTC)
to
WAVES_BTC = pw.AssetPair(pw.WAVES, BTC)

However then i get error:
 File "C:\pywaves\asset.py", line 82, in last
    return str(self.ticker()['24h_close'])
KeyError: '24h_close'

Any ideas?

**Comment by addodelgrossi** [comment]
@ivo1981 BTC is correct ? The correct would not be  

```python
BTC = pw.Asset('8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS')
```
