### ISSUE TITLE
myAddress.assets() not working on testnet

### ISSUE THREAD

**Issue by renickj** [PyWaves/PyWaves#39]
Hi Team when I tried to list all the assets in testnet, I got the below issue, but mainnet works good.

Code:
pw.setChain("testnet")
myAddress = pw.Address('3MpCH9ChCKbN5UYu6V8PrwrPJXVTsaGF1kn')
print(myAddress.assets());

Logs:
Traceback (most recent call last):
  File "wavesBalance.py", line 18, in <module>
    print(myAddress.assets());
  File "C:\Users\renick.j\PycharmProjects\wavesrest\venv\lib\site-packages\pywaves\address.py", line 253, in assets
    req = pywaves.wrapper('/assets/balance/%s' % self.address)['balances']
KeyError: 'balances'

**Comment by renickj** [comment]
Issue fixed I replaced pw.setChain("testnet") with pw.setNode('https://testnode1.wavesnodes.com','testnet')
