### ISSUE TITLE
issueAsset supports only latin characters

### ISSUE THREAD

**Issue by ephdtrg** [PyWaves/PyWaves#79]
Hello. When I'm trying to use non-latin characters in field `description` of `issueAsset`, it raises unicode error. But blockchain itself supports this characters when asset is created with Waves client or through signing and broadcasting raw transaction.

```
myAsset = testAddr.issueAsset(name='TEST', description='тест', quantity=100000000, decimals=8)                                       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/euphemia/work/python/mywill_backend/venv/lib/python3.6/site-packages/pywaves/address.py", line 321, in issueAsset
    struct.pack(">Q", txFee) + \
  File "/home/euphemia/work/python/mywill_backend/venv/lib/python3.6/site-packages/pywaves/crypto.py", line 17, in <lambda>
    str2bytes = lambda s: s.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)

'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)

```

It would be good if this library also supported any characters in asset description

**Comment by PyWaves** [comment]
Not supported yet.
